- name: Copy  mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed


- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.umadevops.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes


